import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { createProxyMiddleware } from "http-proxy-middleware";
import {
  createHealthHandler,
  createLogger,
  createMetrics,
  createRateLimiter,
  createRedisClient,
  createRequestLogger,
} from "@hireheaven/common";
import { resolveServiceMap } from "./serviceMap.js";

dotenv.config();

const SERVICE_NAME = "gateway"; // Gives the service a consistent identity to be used by logging, metrics, health checks, etc

const logger = createLogger(SERVICE_NAME);
const { metricsMiddleware, metricsHandler } = createMetrics(SERVICE_NAME);

const redisClient = createRedisClient({
  url: process.env.Redis_url,
  label: "Gateway",
});

const rateLimiter = createRateLimiter(redisClient);

const app = express();

// No body-parsing middleware here on purpose: this app only proxies,
// and consuming the request stream up front would break streaming the
// original (JSON or multipart) body through to the target service.
app.use(cors());
app.use(createRequestLogger(logger));
app.use(metricsMiddleware);   // This lets the system collect things like request counts and timing
app.use(
  rateLimiter({
    windowSeconds: 60,
    maxRequests: 300,
    prefix: "gateway-global",   // It is used to distinguish this limiter's Redis keys/state from other rate limiters
  })
);

// Is the Gateway service alive/healthy useful for load balancers, Docker, Render, Monitoring and Deployment Platforms 
app.get("/health", createHealthHandler(SERVICE_NAME));
// It exposes the metrics generated by the metrics system 
app.get("/metrics", metricsHandler);

const services = resolveServiceMap(process.env);

for (const [mountPath, target] of Object.entries(services)) {
  app.use(
    mountPath,
    createProxyMiddleware({
      target,
      changeOrigin: true,
      // Render's free tier spins a service down after ~15 min idle; a
      // cold start has taken up to ~45s to boot in practice. These are
      // explicit (not relying on http-proxy's own 120s/no-timeout
      // defaults) so a slow-to-wake target isn't cut off early — though
      // if the platform's own inbound request timeout in front of this
      // gateway is shorter than that, raising these alone won't help;
      // the frontend also retries a cold-start 502/503 once or twice as
      // a second line of defense.
      proxyTimeout: 120_000, // time waiting for the target to respond

      timeout: 120_000, // time waiting on the incoming client connection
      
      // Express strips the mount path from req.url before handing off to
      // this middleware; add it back so the target service sees the same
      // full path it was written to handle (e.g. /api/auth/login).
      pathRewrite: (path) => `${mountPath}${path}`,
      on: {
        error: (err, _req, res) => {
          logger.error({ err, target }, "proxy request failed");
          if ("writeHead" in res) {
            res.writeHead(502, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ message: "Upstream service unavailable" }));
          }
        },
      },
    })
  );
}

app.use((req, res) => {
  res.status(404).json({ message: "Route not found" });
});

const PORT = process.env.PORT || 8080;

app.listen(PORT, () => {
  logger.info(`Gateway is running on http://localhost:${PORT}`);
});
